version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
artifacts:
  type: zip
  files:
    - Frontend/FrontEndUI.png
    - Frontend/index.css
    - Frontend/index.html    
