version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - mkdir build-output
      - cp -R Frontend/ build-output
  post_build:
    commands:
      - mv build-output/**/* ./
      - mv build-output/* ./
      - rm -R build-output
artifacts:
  files:
    - '**/*'
