AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::912884973146:role/service-role/search-photos-role-fuqp5pcm'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      Layers:
        - >-
          arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-opensearch-py:2
        - 'arn:aws:lambda:us-west-2:770693421928:layer:Klayers-p38-requests:2'

  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::912884973146:role/service-role/index-photos-role-iwa09eou'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
      Layers:
        - >-
          arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-opensearch-py:2
        - 'arn:aws:lambda:us-west-2:770693421928:layer:Klayers-p38-requests:2'
  Bucket1:
    Type: 'AWS::S3::Bucket'
